### ISSUE TITLE
Request: Add app to f-droid

### ISSUE THREAD

**Issue by huuhaa** [Windscribe/Android-App#1]
Nice to see [feedback](https://feedback.windscribe.com/posts/251/open-source-app-and-include-to-f-droid) finally at this stage, source actually opened. Now for the second part of that suggestion, it's more natural to continue that part in here..

So my request is to add app to f-droid. Sure for that to be done, you probably have some changes to be made. Is it ok by you that your app will be included at f-droid when it passes f-droid criteria?

[Submitting to F-Droid Quick Start Guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/)

They usually are also very helpful, if help is needed.

**Comment by Ginder-Singh** [comment]
yes this is already in our roadmap.

**Comment by IzzySoft** [comment]
Two requirements I see amiss on a quick check:

* a F/LOSS license (approved by OSI/FSF, [see here](https://spdx.org/licenses/)
* [Fastlane Structures](https://gitlab.com/-/snippets/1895688) to provide metadata like description & screenshots

Thanks for having it on your roadmap already, looking forward to it! Somebody already [opened an RFP](https://gitlab.com/fdroid/rfp/-/issues/2382) (Request For Packaging) for your app :smile:

**Comment by huuhaa** [comment]
@IzzySoft Yes, it was me who leaved RFP, but I did have some reasonings to do so..

1) Quite many times I've seen project needs help from f-droid side and usually it's actually you who steps in at first, but for that project needs to agree on implementation at f-droid..
2) For me that "yes this is already in our roadmap." didn't actually say much. Is it at 5 year plan, a year, two?? Do they need your help when it's that time? But it did tell to me, that they do agree on implementation to f-droid.
3) I tried first suggest this at f-droid forums, to get this notified and maybe ready to help here if needed, but... I was suggested to leave RFP by f-droid admin, cause thread where I suggested, was meant to kind of apps which aren't be done but  what kind of apps are missed..

Anyway, it might have been more reasonable to suggest those by other ways, but what is that correct way? How is it usually done that some suggest project to f-droid and people from there gives some tips at that issue on github?  I now tried one way, was directed to other by admin and when followed that tip, got laughed for it...

**Comment by IzzySoft** [comment]
Wll, it was the right approach IMHO. How else should you know about open points you're not aware of? That's what IssueBot is for. So opening an RFP also means having your app scanned and getting an evaluation. So now it's in the hands of the devs here to see if they tackle the issues so the RFP can proceed – or not, and the RFP must be closed again as F-Droid cannot process it.

**Comment by Ginder-Singh** [comment]
This is in our 3.8 roadmap . I am hoping to get this in to f-droid by end of April 2023. RFP can be closed for now. We will open one once we are ready.

**Comment by IzzySoft** [comment]
Thanks @Ginder-Singh! April is just a month ahead, so I'd say we can leave the RFP open until then. I've added a note there and set a due-date to check back with you should we have not heard from you until mid-May.

**Comment by Ginder-Singh** [comment]
@IzzySoft we have two versions to app one is for tv and one for mobile. They both have same package name but different version codes. Is there something special i need to do ?

**Comment by IzzySoft** [comment]
I assume the two use different build flavors or build from different directories (my guess: `mobile/` vs. `tv/` to use the correct `build.gradle` – which is what the `subdir:` statement is for), so the build block in the F-Droid metadata can use that to make clear.

At the RFP, issuebot might still be confused as it cannot know where to enter. So if you'd leave the corresponding hints (or open the MR yourself), that can be handled.

**Comment by IzzySoft** [comment]
As the due-date is just reached (I just received the notification): Could you please chime in there and state where we stand? From the issuebot report (which we can renew if you say things changed):

* BillingClient is a show-stopper and neededs to be removed¹
* `fastlane/metadata/andrroid/en-US` must have at least `short_description.txt` and `full_description.txt` (nice btw that you already have per-release changelogs there!)
* pre-built binaries (`*.jar`, `*.aar`, `*.so` etc) are not allowed, there seem to be quite a few in your source tree
* Firebase is a show-stopper (proprietary)

¹ for the F-Droid build

So where do we stand with those? I'll now raise the due-date one more time to give you the chance to address those :wink:

**Comment by Ginder-Singh** [comment]
Some of changes I made this week.
1. Separated project in to two flavours google and fdroid.
2. All billing (amazon, google) and proprietary (firebase) moved to google flavour.
3. Removed all libs(.aar) and they now being hosted on jitpack (wstunnel)
4. Added short description, full description , screenshot etc.

**Comment by IzzySoft** [comment]
Thanks! Updated the RFP and triggered the bot again.

**Comment by Ginder-Singh** [comment]
@IzzySoft So i tried building windscribe with fdroid . I was able to figure most of it. One thing that is unresolved now is strongswan binaries we use. this would require building strongswan with openssl + ndk . I get this error
"Job's log exceeded limit of 4194304 bytes.
Job execution will continue but no more output will be collected." . but Job actually fails. we usually build these locally and add prebult ones to the app. Is there a way i can add them prebuilt or you can find me some solution to the error.

**Comment by Ginder-Singh** [comment]
@IzzySoft Added merge request [here](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13185)

**Comment by IzzySoft** [comment]
I see licaon is already helping you there (I just cleaned up a bunch of redundant issuebot reports to make that MR easier to follow). However, IMHO BillingClient is a show-stopper, as pointed out. While it is "free" (as in "no monetary charges apply, everyone is allowed to use it") it is not "libre" (it has a proprietary license):

```json
{
  "id": "/com/android/billingclient",
  "emphasize": 1,
  "details": "Google Play Billing Library",
  "mwid": "",
  "anti": ["NonFreeDep","NonFreeNet"],
  "license": "Proprietary"
}
```

Can it be excluded for the F-Droid build?

**Comment by Ginder-Singh** [comment]
MR for this is approved and hoping for being live on Fdroid in few days.
