### ISSUE TITLE
About icon

### ISSUE THREAD

**Issue by BabyOilJohnson** [Windscribe/Android-App#12]
The icon not look good.
![Screenshot_20230729-193237_One UI Home](https://github.com/Windscribe/Android-App/assets/101601874/a17de4c3-2969-46db-a773-a9de99b83d59)

**Comment by Ivantheallknowing** [comment]
That looks like the icon of our Android TV app. You might've installed the incorrect app for your platform.

**Comment by BabyOilJohnson** [comment]
I think so, I should have really looked into it 🤦🏼‍♂️. Sorry about that, so I'm closing.
