### ISSUE TITLE
protocol set issue 

### ISSUE THREAD

**Issue by Saeedsidj** [Windscribe/Android-App#19]
when try to connect with any protocol and its time out and fail to connect , screen showing others protocol to select and try again  , i think there was a countdown timer for when user not click any thing select first protocol by default  . but there is a close icon too and when user close the recommended  protocol screen and click again in on/off button , you will see the protocol has changed to the first one in the recommended protocol in the previous screen .

**Comment by Ginder-Singh** [comment]
Yeah its reproducible. We  will fix it in next release.

**Comment by Ginder-Singh** [comment]
fixed in 3.77
