### ISSUE TITLE
Windscribe timeout and protocol auto-connect issue

### ISSUE THREAD

**Issue by CIAvash** [Windscribe/Android-App#2]
On desktop, Windscribe waits a lot longer(indefinitely?) while connecting to servers, but on Android the timeout is short and quickly tries to connect to another protocol.

And that's not the only issue, this happens even though I've set the protocol connection to manual, so I don't expect it to automatically switch protocols; this is very annoying and makes connecting impossible for free accounts in certain countries.

**Comment by Ginder-Singh** [comment]
Automatic timeout being short is really helpful in most countries where some protocol based block is in place ie. Public networks in restaurants blocking IKEv2.
For manual connection mode we can stop the auto switch from engaging.
Stay tuned for next update.

**Comment by Ginder-Singh** [comment]
added in 3.71
