### ISSUE TITLE
Publish on accrescent

### ISSUE THREAD

**Issue by atlantis451** [Windscribe/Android-App#24]
https://github.com/accrescent/accrescent
https://github.com/accrescent/parcelo Accrescent developer console.

Many people have used any of account, and the accounts are not applied. This is an opportunity for WindScrip high exposure

> Accrescent is a private and secure Android app store built with modern features in mind. It aims to provide a developer-friendly platform and pleasant user experience while enforcing modern security and privacy practices and offering robust validity guarantees for installed apps.

**Comment by Ginder-Singh** [comment]
May be in future but currently we don't see much value to app to another store.
