### ISSUE TITLE
What happened to the commit history?

### ISSUE THREAD

**Issue by ltguillaume** [Windscribe/Android-App#33]
- Every single commit just reads `Updated to 3.80`
- It's impossible to compare tag `3.80` with any other tag: `There isn’t anything to compare. v3.79 and v3.80 are entirely different commit histories.`

Can you please change the way you push(ed) these commits, allowing for proper commit messages that actually describe the change and the ability to compare commit histories? The way this is currently done makes it impossible to properly check what changes have been made, which is a significant part of the point of open-sourcing to begin with.

**Comment by Ginder-Singh** [comment]
Sorry bad my deploy script messed up. I have pushed the changes now + last 4 tags to match history.
[3.79 > 3.80](https://github.com/Windscribe/Android-App/compare/3.79.2...3.80)
[3.77 > 3.79](https://github.com/Windscribe/Android-App/compare/3.77...3.79.2)
[3.76 > 3.77](https://github.com/Windscribe/Android-App/compare/3.76...3.77)
