### ISSUE TITLE
Weblate Translation

### ISSUE THREAD

**Issue by GET100PERCENT** [Windscribe/Android-App#4]
It will be helpful if a facility is provided for contributors to translate Windscribe to their local languages using weblate.

**Comment by Ginder-Singh** [comment]
Currently we don't have a web admin for translations. if you can let me know which language you would like to help us translate I can provide you a .xlf file which you should be able to open in most translating software.

**Comment by GET100PERCENT** [comment]
I want to  translate the app in to "Odia".
Can i translate the "strings.xml" file?
https://github.com/Windscribe/Android-App/blob/main/base/src/main/res/values/strings.xml

**Comment by Ginder-Singh** [comment]
yes you can.

**Comment by GET100PERCENT** [comment]
I have an examination, so i shall  start translating after June. If possible please keep the issue open.

**Comment by GET100PERCENT** [comment]
If you want to close it, then you can . After translating i will make a fork of the project and send a pull request.

**Comment by GET100PERCENT** [comment]
I have completed the Odia translation and sent a pull request.
