### ISSUE TITLE
Sharing below link for Windscribe Team to refer and get some new ideas and find Missing Features and Competitor Comparison.

### ISSUE THREAD

**Issue by libbyslayer** [Windscribe/Android-App#40]
Sharing below link for Windscribe Team to refer and get some new ideas and find Missing Features and Competitor Comparison.

https://docs.google.com/spreadsheets/d/1ijfqfLrJWLUVBfJZ_YalVpstWsjw-JGzkvMd6u2jqEk/edit?gid=231869418#gid=231869418

**Comment by yegors** [comment]
Unsure who made this, but it's hilarious.
